//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace MusicBeePlugin {
    using System;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicBeePlugin.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string FormTitle {
            get {
                return ResourceManager.GetString("FormTitle", resourceCulture);
            }
        }
        
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        internal static string AutoSaveZoom {
            get {
                return ResourceManager.GetString("AutoSaveZoom", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string RestartHint {
            get {
                return ResourceManager.GetString("RestartHint", resourceCulture);
            }
        }
        
        internal static string ShowAddressBar {
            get {
                return ResourceManager.GetString("ShowAddressBar", resourceCulture);
            }
        }
        
        internal static string DarkModeLabel {
            get {
                return ResourceManager.GetString("DarkModeLabel", resourceCulture);
            }
        }
        
        internal static string DarkModeDefault {
            get {
                return ResourceManager.GetString("DarkModeDefault", resourceCulture);
            }
        }
        
        internal static string DarkModeDark {
            get {
                return ResourceManager.GetString("DarkModeDark", resourceCulture);
            }
        }
        
        internal static string DarkModeMusicBeeTheme {
            get {
                return ResourceManager.GetString("DarkModeMusicBeeTheme", resourceCulture);
            }
        }
        
        internal static string EnableExtensions {
            get {
                return ResourceManager.GetString("EnableExtensions", resourceCulture);
            }
        }
        
        internal static string OpenExtensionsFolder {
            get {
                return ResourceManager.GetString("OpenExtensionsFolder", resourceCulture);
            }
        }
        
        internal static string InstallUnpackedExtension {
            get {
                return ResourceManager.GetString("InstallUnpackedExtension", resourceCulture);
            }
        }
        
        internal static string InstallZipCrxExtension {
            get {
                return ResourceManager.GetString("InstallZipCrxExtension", resourceCulture);
            }
        }
        
        internal static string SelectExtensionFolder {
            get {
                return ResourceManager.GetString("SelectExtensionFolder", resourceCulture);
            }
        }
        
        internal static string SelectExtensionFile {
            get {
                return ResourceManager.GetString("SelectExtensionFile", resourceCulture);
            }
        }
        
        internal static string ExtensionInstalled {
            get {
                return ResourceManager.GetString("ExtensionInstalled", resourceCulture);
            }
        }
        
        internal static string ExtensionInstallFailed {
            get {
                return ResourceManager.GetString("ExtensionInstallFailed", resourceCulture);
            }
        }
        
        internal static string InstalledExtensions {
            get {
                return ResourceManager.GetString("InstalledExtensions", resourceCulture);
            }
        }
        
        internal static string ExtensionName {
            get {
                return ResourceManager.GetString("ExtensionName", resourceCulture);
            }
        }
        
        internal static string ExtensionVersion {
            get {
                return ResourceManager.GetString("ExtensionVersion", resourceCulture);
            }
        }
        
        internal static string ExtensionEnabled {
            get {
                return ResourceManager.GetString("ExtensionEnabled", resourceCulture);
            }
        }
        
        internal static string ExtensionAction {
            get {
                return ResourceManager.GetString("ExtensionAction", resourceCulture);
            }
        }
        
        internal static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        internal static string ExtensionUninstalled {
            get {
                return ResourceManager.GetString("ExtensionUninstalled", resourceCulture);
            }
        }
        
        internal static string ExtensionUninstallFailed {
            get {
                return ResourceManager.GetString("ExtensionUninstallFailed", resourceCulture);
            }
        }
        
        internal static string NoExtensionsInstalled {
            get {
                return ResourceManager.GetString("NoExtensionsInstalled", resourceCulture);
            }
        }
        
        internal static string ConfirmUninstall {
            get {
                return ResourceManager.GetString("ConfirmUninstall", resourceCulture);
            }
        }
        
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        internal static string EnableExtension {
            get {
                return ResourceManager.GetString("EnableExtension", resourceCulture);
            }
        }
        
        internal static string DisableExtension {
            get {
                return ResourceManager.GetString("DisableExtension", resourceCulture);
            }
        }
        
        internal static string ExtensionEnabledMessage {
            get {
                return ResourceManager.GetString("ExtensionEnabled", resourceCulture);
            }
        }
        
        internal static string ExtensionDisabled {
            get {
                return ResourceManager.GetString("ExtensionDisabled", resourceCulture);
            }
        }
        
        internal static string ToggleExtensionFailed {
            get {
                return ResourceManager.GetString("ToggleExtensionFailed", resourceCulture);
            }
        }
        
        internal static string ManifestNotFound {
            get {
                return ResourceManager.GetString("ManifestNotFound", resourceCulture);
            }
        }
        
        internal static string RestartRequiredForExtensionChanges {
            get {
                return ResourceManager.GetString("RestartRequiredForExtensionChanges", resourceCulture);
            }
        }
        
        internal static string ProjectLink {
            get {
                return ResourceManager.GetString("ProjectLink", resourceCulture);
            }
        }
        
        internal static string ProjectLinkUrl {
            get {
                return ResourceManager.GetString("ProjectLinkUrl", resourceCulture);
            }
        }
    }
}
